name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: edb3ef25c182dd7413b9fc4145e9f526
        file_path: resume.json
